# This is the configuration file for catnap.
# Here you can configure the stat colors,
# stat names, stat icons and more!
#
# https://github.com/iinsertNameHere/catnap

##############################################
##          FetchInfo stats Config          ##
##############################################
[stats]
username = { icon = " ", name = "user", color = "{CN}" }
hostname = { icon = " ", name = "host", color = "{CN}" }
distro = { icon = " ", name = "dist", color = "{CN}" }
sep_1 = ""
desktop = { icon = " ", name = "de", color = "{CN}" }
terminal = { icon = " ", name = "term", color = "(CN)" }
shell = { icon = " ", name = "sh", color = "{CN}" }
sep_2 = ""
cpu       = {icon = " ", name = "cpu", color = "(CN)"}
gpu       = {icon = "󱔐 ", name = "gpu", color = "(CN)"}
# battery   = {icon = " ", name = "battery", color = "(RD)"}
memory    = {icon = " ", name = "mem", color = "{CN}"}
# The following stats do not work on MacOS and the BSDs.
# disk_0    = {icon = " ", name = "disk", color = "(WE)"}
sep_color = "SEPARATOR"
colors = { icon = " ", name = "colors", color = "!DT!", symbol = "" }

##############################################
##               Misc Config                ##
##############################################
[misc]
borderstyle = "line"
layout = "Inline"    # [Inline, ArtOnTop, StatsOnTop]
stats_margin_top = 0
location = ""        # Used for fetching weather; leave empty to use the location of your IP; check https://wttr.in/:help for supported location types

[misc.figletLogos] # Requires Figlet.
enable = false
color = "(CN)"
font = "slant"
margin = [0, 0, 0,]

[misc.imageMode] # Requires Viu.
enable = false
path = "/path/to/some/image.png" # Please only use absolute paths.
scale = 18
margin = [2, 2, 3,]
