$mononoke = $HOME/.config/hypr/wallpaper/mononoke.png
$mononoke_dark = $HOME/.config/hypr/wallpaper/mononoke-dark.png
preload = $mononoke_dark
preload = $mononoke

wallpaper {
  monitor =
  path = $mononoke_dark
}

#enable splash text rendering over the wallpaper
splash = false

# fully disable ipc
# ipc = off
